/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_dodo;

/**
 *
 * @author Auguis
 */
public class REGISTER extends javax.swing.JFrame {

    /**
     * Creates new form REGISTER
     */
    public REGISTER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hans1 = new javax.swing.JTextField();
        hans2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        hans3 = new javax.swing.JTextField();
        hans4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField3 = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hans1.setBackground(new java.awt.Color(153, 153, 153));
        hans1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        hans1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hans1.setText("Quickie Bites");
        hans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hans1ActionPerformed(evt);
            }
        });
        jPanel1.add(hans1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 230, 40));

        hans2.setBackground(new java.awt.Color(153, 153, 153));
        hans2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        hans2.setText("Email");
        hans2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hans2ActionPerformed(evt);
            }
        });
        jPanel1.add(hans2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        hans3.setBackground(new java.awt.Color(153, 153, 153));
        hans3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        hans3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        hans3.setText("Password");
        hans3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hans3ActionPerformed(evt);
            }
        });
        jPanel1.add(hans3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 33));

        hans4.setBackground(new java.awt.Color(153, 153, 153));
        hans4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        hans4.setText("Confirm Password");
        hans4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hans4ActionPerformed(evt);
            }
        });
        jPanel1.add(hans4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("REGISTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 130, -1));

        jPasswordField3.setText("jPasswordField3");
        jPanel1.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 340, 40));

        jPasswordField1.setText("jPasswordField1");
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 340, 40));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 340, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hans1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hans1ActionPerformed

    private void hans2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hans2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hans2ActionPerformed

    private void hans3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hans3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hans3ActionPerformed

    private void hans4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hans4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hans4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hans1;
    private javax.swing.JTextField hans2;
    private javax.swing.JTextField hans3;
    private javax.swing.JTextField hans4;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
